###CREATE PERFORMANCE SUMMARY
POST http://localhost:5500/performance/create
Content-Type: application/json


{
    "taskCompleted":6,
    "hoursworked": 20
}

###VIEW ALL RECORDS
POST  http://localhost:5500/performance/showperformance-records
Content-Type: application/json

{
  "performance": {
    "taskCompleted": 10,
    "hoursworked": 40
  },
  "userdetails": {
    "username": "Glen",
    "email": "glen@example.com"
  }
}
