###CREATE EVENT
POST http://localhost:5500/jobs/create
Content-Type: application/json


{
    "image":"pexels-emma-bauso-1183828-2253842.jpg",
    "title": "Printer",
    "description": "Printing papers",
    "location": "Nairobi",
    "status": "Open",
    "salary":4500.00
    
   
}

###UPDATE EVENT
PUT http://localhost:5500/jobs/08c0af61-ce93-4a4b-be21-ffad81366a26
Content-Type: application/json


{
     "image":"pexels-emma-bauso-1183828-2253842.jpg",
    "title": "receptionist",
    "description": "directing visitors",
    "location": "Garissa",
    "status": "Open",
    "salary":4500.00

   
}

###DELETE JOBS
DELETE http://localhost:5500/jobs/1cca19ac-9749-476e-a328-91d13d4b69bd

###VIEW ALL JOBS
GET http://localhost:5500/jobs/all-jobs
Content-Type: application/json

###VIEW ONE JOB
GET http://localhost:5500/jobs/ca19ca73-cda4-49ee-a4e7-d0647f07b33b